shivam/urls.py
from django.contrib import admin
from django.urls import path
from realty import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage,name='homepage'),
    path('about_us/', views.about_us, name='about_us'),
    path('contact/', views.contact, name='contact'),
    path('property/<pk>/', views.property, name='property'),

    ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

realty/models.py
from django.db import models
from django.forms import ModelForm
# Create your models here.
transaction_type_choices=(
    ('buy','Buy'),
    ('rent','Rent'),
    ('sell', 'Sell')
)
area_choices=(
    ('Bandra E', 'Bandra East'),
    ('Bandra W', 'Bandra West'),
    ('Khar E', 'Khar East'),
    ('Khar W', 'Khar West'),
    ('Santacruz E', 'Santacruz East'),
    ('Santacruz W', 'Santacruz West'),
    ('Parle E', 'Vile-Parle East'),
    ('Parle W', 'Vile-Parle West'),
    ('Andheri E', 'Andheri East'),
    ('Andheri W', 'Andheri West'),
)
property_choices=(
    ('apartment','Apartment'),
    ('house/villa','House/Villa'),
    ('plot','Plot')
)
purpose_choices=(
    ('residential','Residential'),
    ('commercial','Commercial')
)
furnished_choices=(
    ('fully-furnished','Fully Furnished'),
    ('semi-furnished','Semi Furnished'),
    ('non-furnished','Non Furnished')
)
class Booking(models.Model):
    transaction_type=models.CharField(max_length=10, choices=transaction_type_choices, default='buy')
    name=models.CharField(max_length=50, null=False, blank=False)
    message_id=models.AutoField(primary_key=True)
    property_type=models.CharField(max_length=20, blank=False, null=False, default='apartment', choices=property_choices)
    bedrooms=models.IntegerField(null=True, blank=True)
    purpose=models.CharField(max_length=20, choices=purpose_choices, default='residential')
    square_feet=models.CharField(max_length=20, blank=True, null=True)
    
    furniture=models.CharField(max_length=20, choices=furnished_choices, default='fully-furnished')
    area=models.CharField(max_length=50, choices=area_choices, blank=True, null=True)
    landmark=models.CharField(max_length=20,null=True, blank=True)
    budget=models.CharField(max_length=50, null=True, blank=True)
    email=models.EmailField(null=False, blank=False)
    phone=models.CharField(max_length=20,blank=True, null=True)
    date=models.DateTimeField(auto_now_add=True, null=True, blank=True)
    additional_message=models.TextField(max_length=250,null=True, blank=True)
    def __str__(self):
        return self.name
class Contact(models.Model):
    contact_id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=50, null=False, blank=False)
    message=models.TextField(max_length=250, null=False, blank=False)
    email=models.EmailField(blank=False, null=False)
    phone=models.CharField(max_length=20,blank=True, null=True)
    date=models.DateTimeField(auto_now_add=True, blank=True, null=True)
    def __str__(self):
        return self.name

class BookingForm(ModelForm):
    class Meta:
        model=Booking
        fields='__all__'
        labels={
            "transaction_type":"You want to?",
            "budget":"Price (In Rupees)"
        }

class ContactForm(ModelForm):
    class Meta:
        model=Contact
        fields='__all__'

class PropertyType(models.Model):
    type_name=models.CharField(max_length=20, null=False, blank=False)
    def __str__(self):
        return self.type_name
    
class Listing(models.Model):
    
    property_name=models.CharField(max_length=100, null=False, blank=False)
    property_rate=models.CharField(max_length=20, null=False, blank=True)
    property_size=models.CharField(max_length=20, blank=True, null=True)
    property_attributes=models.CharField(max_length=30, null=False, blank=False)
    property_type=models.ForeignKey(PropertyType,blank=False, null= False, on_delete=models.CASCADE)
    property_transaction_type=models.CharField(max_length=10, choices=transaction_type_choices, default='buy')
    property_intro=models.CharField(max_length=50, null=False, blank=False)
    property_rooms=models.IntegerField(blank=True, null=True)
    property_bathrooms=models.IntegerField(blank=True, null=True)
    property_landmark=models.CharField(max_length=20, null=False)
    property_address=models.TextField(blank=False, null=False)
    property_description=models.TextField(null=False, blank=False)
    property_thumbnail=models.ImageField(null=False, blank=True, upload_to='uploads')
    property_image1=models.ImageField(blank=True, null=True, upload_to='uploads')
    property_image2=models.ImageField(blank=True, null=True, upload_to='uploads')
    property_image3=models.ImageField(blank=True, null=True, upload_to='uploads')
    property_image4=models.ImageField(blank=True, null=True, upload_to='uploads')
    property_image5=models.ImageField(blank=True, null=True, upload_to='uploads')

    
    def __str__(self):
        return self.property_name


class Customers(models.Model):
    customer_name=models.CharField(max_length=20, null=False, blank=False)
    customer_phone=models.IntegerField(null=False, blank=False)
    customer_email=models.EmailField(null=True, blank=True)
    property_reference=models.ForeignKey(Listing, null=True, blank=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.customer_name

class CustomerForm(ModelForm):
    class Meta:
        model=Customers
        fields='__all__'

    

realty/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Booking, Contact, ContactForm, BookingForm, Listing, CustomerForm
from django.contrib import messages


def homepage(request):
    listings_obj=Listing.objects.all()
    if request.method=='POST':
        
        bForm=BookingForm(request.POST)


        if bForm.is_valid():
            bForm.save()
        
            bForm=BookingForm()
            messages.success(request, 'Thank you for showing interest. We will get back to you soon.')
        
    else:
       
        bForm=BookingForm()
    return render(request,'home.html',{'bForm':bForm,'listings':listings_obj})    
        

def contact(request):
    
    if request.method=='POST':
        
        cForm=ContactForm(request.POST)
        if cForm.is_valid():
       
            cForm.save()

            cForm=ContactForm()
            messages.success(request, 'Thank you for showing interest. We will get back to you soon.')
        
    else:
       
        cForm=ContactForm()
    return render(request,'contact.html',{'cForm':cForm,})  

def about_us(request):
    return render(request,'about_us.html')

def property(request, pk):
    prop_id=pk
    property_obj=Listing.objects.get(pk=prop_id)
    if request.method=='POST':
        
        bForm=CustomerForm(request.POST)


        if bForm.is_valid():
            temp=bForm.save(commit=False)
            temp.property_type=property_obj
            temp.save()
        
            bForm=CustomerForm()
            messages.success(request, 'Thank you for showing interest. We will get back to you soon.')
        
    else:
       
        bForm=CustomerForm()
    return render(request,'property.html',{'property':property_obj,'bForm':bForm})  

templates/about_us.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
{% load crispy_forms_tags %}
<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>Liaision - Real Estate Agency | Contact</title>

    <!-- Favicon  -->
    <link rel="icon" href="{% static "img/core-img/favicon.ico" %}">

    <!-- Style CSS -->
    <link rel="stylesheet" href="{% static "style.css" %}">

</head>

<body>
    <!-- Preloader -->
    <div id="preloader">
        <div class="south-load"></div>
    </div>

    <!-- ##### Header Area Start ##### -->
    <header class="header-area">

        <!-- Top Header Area -->
        <div class="top-header-area">
            <div class="h-100 d-md-flex justify-content-between align-items-center">
                <div class="email-address">
                    <a href="mailto:contact@southtemplate.com">contact@liaision.com</a>
                </div>
                <div class="phone-number d-flex">
                    <div class="icon">
                        <img src="{% static "img/icons/phone-call.png" %}" alt="">
                    </div>
                    <div class="number">
                        <a>+91 972637263</a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Main Header Area -->
        <div class="main-header-area" id="stickyHeader">
            <div class="classy-nav-container breakpoint-off">
                <!-- Classy Menu -->
                <nav class="classy-navbar justify-content-between" id="southNav">

                    <!-- Logo -->
                    <a class="nav-brand" href="/"><img src="{% static "img/core-img/logo.png" %}" alt=""></a>

                    <!-- Navbar Toggler -->
                    <div class="classy-navbar-toggler">
                        <span class="navbarToggler"><span></span><span></span><span></span></span>
                    </div>

                    <!-- Menu -->
                    <div class="classy-menu">

                        <!-- close btn -->
                        <div class="classycloseIcon">
                            <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                        </div>

                        <!-- Nav Start -->
                        <div class="classynav">
                            <ul>
                                <li><a href="/">Home</a></li>
                                
                                <li><a href="/about_us">About Us</a></li>
                                
                                
                                <li><a href="/contact">Contact</a></li>
                            </ul>

                            
                            

                        
                        </div>
                        <!-- Nav End -->
                    </div>
                </nav>
            </div>
        </div>
    </header>
    <!-- ##### Header Area End ##### -->

    <!-- ##### Hero Area Start ##### -->
    <section class="hero-area">
        <div class="hero-slides owl-carousel">
            <!-- Single Hero Slide -->
            <div class="single-hero-slide bg-img" style="background-image: url({% static "img/bg-img/hero1.jpg" %});">
                <div class="container h-100">
                    <div class="row h-100 align-items-center">
                        <div class="col-12">
                            <div class="hero-slides-content">
                                <h2 data-animation="fadeInUp" data-delay="100ms">About Us</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Single Hero Slide -->
            <div class="single-hero-slide bg-img" style="background-image: url({% static "img/bg-img/hero2.jpg" %});">
                <div class="container h-100">
                    <div class="row h-100 align-items-center">
                        <div class="col-12">
                            <div class="hero-slides-content">
                                <h2 data-animation="fadeInUp" data-delay="100ms">About Us</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Single Hero Slide -->
            <div class="single-hero-slide bg-img" style="background-image: url({% static "img/bg-img/hero3.jpg" %});">
                <div class="container h-100">
                    <div class="row h-100 align-items-center">
                        <div class="col-12">
                            <div class="hero-slides-content">
                                <h2 data-animation="fadeInUp" data-delay="100ms">About Us</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Hero Area End ##### -->

    <!-- ##### Advance Search Area Start ##### -->
    <div class="south-search-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="advanced-search-form">
                        <!-- Search Title -->
                        <div class="search-title">
                            <p>Who We Are</p>
                        </div>
                        <p>Whether you are a buyer or a seller of property, a local resident or a newcomer to our magic city of Mumbai, we are here to listen.

                                At Liaision Realty we understand that Real Estate is about real people who want real results. Our agency service is rich in integrity and commonsense, high in results and proven customer satisfaction. Our agents are down to earth, hardworking, straight talking professionals.
                                
                                Liaision Realty, where it really is all about U.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Advance Search Area End ##### -->

    

    <!-- ##### Call To Action Area Start ##### -->
    <section class="call-to-action-area bg-fixed bg-overlay-black" style="background-image: url({% static "img/bg-img/cta.jpg" %})">
        <div class="container h-100">
            <div class="row align-items-center h-100">
                <div class="col-12">
                    <div class="cta-content text-center">
                        <h2 class="wow fadeInUp" data-wow-delay="300ms">Are you looking for a place to rent or buy in Mumbai?</h2>
                        
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Call To Action Area End ##### -->

    

  

    <!-- ##### Footer Area Start ##### -->
    <footer class="footer-area section-padding-100-0 bg-img gradient-background-overlay" style="background-image: url(img/bg-img/cta.jpg);">
        <!-- Main Footer Area -->
        <div class="main-footer-area">
            <div class="container">
                <div class="row">

                    <!-- Single Footer Widget -->
                    <div class="col-12 col-sm-6 col-xl-3">
                        <div class="footer-widget-area mb-100">
                            <!-- Widget Title -->
                            <div class="widget-title">
                                <h6>About Us</h6>
                            </div>

                            <img src="{% static "img/bg-img/footer.jpg" %}" alt="">
                            <div class="footer-logo my-4">
                                <img src="{% static "img/core-img/logo.png" %}" alt="">
                            </div>
                            <p>Integer nec bibendum lacus. Suspen disse dictum enim sit amet libero males uada feugiat. Praesent malesuada.</p>
                        </div>
                    </div>

                    <!-- Single Footer Widget -->
                    <div class="col-12 col-sm-6 col-xl-3">
                        <div class="footer-widget-area mb-100">
                            <!-- Widget Title -->
                            <div class="widget-title">
                                <h6>Hours</h6>
                            </div>
                            <!-- Office Hours -->
                            <div class="weekly-office-hours">
                                <ul>
                                    <li class="d-flex align-items-center justify-content-between"><span>Monday - Friday</span> <span>09 AM - 19 PM</span></li>
                                    <li class="d-flex align-items-center justify-content-between"><span>Saturday</span> <span>09 AM - 14 PM</span></li>
                                    <li class="d-flex align-items-center justify-content-between"><span>Sunday</span> <span>Closed</span></li>
                                </ul>
                            </div>
                            <!-- Address -->
                            <div class="address">
                                    <h6><img src="{% static "img/icons/phone-call.png" %}" alt=""> +91 9847587456</h6>
                                    <h6><img src="{% static "img/icons/envelope.png" %}" alt=""> office@liaision.com</h6>
                                    <h6><img src="{% static "img/icons/location.png" %}" alt=""> Golibaar, Santacruz East, Mumbai, Maharashtra</h6>
                                </div>
                        </div>
                    </div>

                    <!-- Single Footer Widget -->
                    <div class="col-12 col-sm-6 col-xl-3">
                        <div class="footer-widget-area mb-100">
                            <!-- Widget Title -->
                            <div class="widget-title">
                                <h6>Useful Links</h6>
                            </div>
                            <!-- Nav -->
                            <ul class="useful-links-nav d-flex align-items-center">
                                <li><a href="/">Home</a></li>
                                <li><a href="/about_us">About us</a></li>
                                <li><a href="/contact">Contact us</a></li>
                                
                                
                            </ul>
                        </div>
                    </div>


                </div>
            </div>
        </div>

        <!-- Copywrite Text -->
        <div class="copywrite-text d-flex align-items-center justify-content-center">
            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->

    <!-- jQuery (Necessary for All JavaScript Plugins) -->
    <script src="{% static "js/jquery/jquery-2.2.4.min.js" %}"></script>
    <!-- Popper js -->
    <script src="{% static "js/popper.min.js" %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <!-- Plugins js -->
    <script src="{% static "js/plugins.js" %}"></script>
    <script src="{% static "js/classy-nav.min.js" %}"></script>
    <script src="{% static "js/jquery-ui.min.js" %}"></script>
    <!-- Active js -->
    <script src="{% static "js/active.js" %}"></script>

</body>

</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
{% block title %}

{% endblock %}  



</head>
<body>



	<!-- Header -->

	<header class="header">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="header_content d-flex flex-row align-items-center justify-content-start">
						<div class="logo">
							<a href="#"><img src="{% static 'images/logo.png' %}" alt=""></a>
						</div>
						<nav class="main_nav">
							<ul>
								<li class="active"><a href="/">Home</a></li>
								<li><a href="/about">About us</a></li>
								
								
								<li><a href="/contact">Contact</a></li>
							</ul>
						</nav>
						<div class="phone_num ml-auto">
							<div class="phone_num_inner">
								<img src="{% static "images/phone.png" %}" alt=""><span>652-345 3222 11</span>
							</div>
						</div>
						<div class="hamburger ml-auto"><i class="fa fa-bars" aria-hidden="true"></i></div>
					</div>
				</div>
			</div>
		</div>
	</header>

	<!-- Menu -->

	<div class="menu trans_500">
		<div class="menu_content d-flex flex-column align-items-center justify-content-center text-center">
			<div class="menu_close_container"><div class="menu_close"></div></div>
			<div class="logo menu_logo">
				<a href="#">
					<div class="logo_container d-flex flex-row align-items-start justify-content-start">
						<div class="logo_image"><div><img src="{% static 'images/logo.png' %}" alt=""></div></div>
					</div>
				</a>
			</div>
			<ul>
				<li class="menu_item"><a href="/">Home</a></li>
				<li class="menu_item"><a href="/about">About us</a></li>
				
				<li class="menu_item"><a href="/contact">Contact</a></li>
			</ul>
		</div>
		<div class="menu_phone"><span>call us: </span>652 345 3222 11</div>
	</div>
	
	<!-- Home -->

	{% block home %}
	{% endblock %}

	<!-- Home Search -->
	

	<!-- Recent -->
	{% block listings %}
	{% endblock %}
	
		
			
					
						
							{% block enq_form %}
							{% endblock %}
						
				
				
		


	

	


	

	<!-- Footer -->

	<footer class="footer" style="padding-top:4%">
			<div class="footer_main">
					<div class="container">
						<div class="row">
							<div class="col-lg-3">
								<div class="footer_logo"><a href="#"><img src="{% static 'images/logo_large.png' %}" alt=""></a></div>
							</div>
							<div class="col-lg-9 d-flex flex-column align-items-start justify-content-end">
								<div class="footer_title">Latest Properties</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-3 footer_col">
								<div class="footer_about">
									<div class="footer_about_text">Donec in tempus leo. Aenean ultricies mauris sed quam lacinia lobortis. Cras ut vestibulum enim, in gravida nulla. Curab itur ornare nisl at sagittis cursus.</div>
								</div>
							</div>
							<div class="col-lg-3 footer_col">
								<div class="footer_latest d-flex flex-row align-items-start justify-content-start">
									<div><div class="footer_latest_image"><img src="{% static 'images/footer_latest_1.jpg' %}" alt=""></div></div>
									<div class="footer_latest_content">
										<div class="footer_latest_location">Miami</div>
										<div class="footer_latest_name"><a href="#">Sea view property</a></div>
										<div class="footer_latest_price">$ 1. 234 981</div>
									</div>
								</div>
							</div>
							
						</div>
					</div>
				</div>
		
		<div class="footer_bar" style="padding-top:5%">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="footer_bar_content d-flex flex-row align-items-center justify-content-start">
							<div class="cr"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</div>
							<div class="footer_nav">
								<ul>
									<li><a href="/">Home</a></li>
									<li><a href="/about">About us</a></li>
									<li><a href="/listings">Properties</a></li>
									
									<li><a href="/contact">Contact</a></li>
								</ul>
							</div>
							<div class="footer_phone ml-auto"><span>call us: </span>652 345 3222 11</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>

{% block jsscript %}

{% endblock %}
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
{% block title %}
<title>Contact</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="Bluesky template project">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/rangeslider.js-2.3.0/rangeslider.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/contact.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/contact_responsive.css' %}">
{% endblock %}
</head>
<body>
	



	<!-- Header -->

	

	<!-- Menu -->

	
	
	<!-- Home -->
	{% block home %}
	<div class="home">
		<div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="{% static 'images/contact.jpg' %}" data-speed="0.8"></div>
		<div class="home_container">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="home_content d-flex flex-row align-items-end justify-content-start">
							<div class="home_title">Contact</div>
							
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

	<!-- Contact -->

	{% block enq_form %}

	<div class="contact">
		<div class="container">
			<div class="row">

				<!-- Contact Info -->
				<div class="col-lg-4">
					<div class="contact_info">
						<div class="section_title">Get in touch with us</div>
						<div class="section_subtitle">Say hello</div>
						<div class="contact_info_text"><p>Donec ullamcorper nulla non metus auctor fringi lla. Curabitur blandit tempus porttitor.Sed lectus urna, ultricies sit amet risus eget.</p></div>
						<div class="contact_info_content">
							<ul class="contact_info_list">
								<li>
									<div>Address:</div>
									<div>1481 Creekside Lane Avila Beach, CA 93424</div>
								</li>
								<li>
									<div>Phone:</div>
									<div>+53 345 7953 32453</div>
								</li>
								<li>
									<div>Email:</div>
									<div>yourmail@gmail.com</div>
								</li>
							</ul>
						</div>
					</div>
				</div>

				<!-- Contact Form -->
				<div class="col-lg-8">
					<div class="contact_form_container">
							{% if messages %}
							<ul class="messages">
								{% for message in messages %}
								<li class="section_subtitle" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
								{% endfor %}
							</ul>
							{% endif %}
						<form method="post" class="contact_form" id="contact_form">
							{% csrf_token %}
							<div class="row" style="padding-top:2%">
									<!-- Name -->
									<div class="col-lg-6 contact_name_col">
										
										<input type="text" name="name" maxlength="50" required="" id="id_name" class="contact_input" placeholder="Name">
									</div>
									<!-- Email -->
									<div class="col-lg-6">
										
										<input type="email" name="email" maxlength="254" required="" id="id_email" class="contact_input" placeholder="E-mail">
									</div>
								</div>
							<div>
								<input type="text" name="phone" maxlength="20" id="id_phone"class="contact_input" placeholder="Phone">
							</div>
							
							<div>
								<textarea name="message" cols="40" rows="10" maxlength="250" required="" id="id_message" class="contact_textarea contact_input" placeholder="Message"></textarea>
								</div>
							<button class="contact_button button" type="submit">send</button>
						</form>
						
					</div>
				</div>
			</div>
		</div>
	</div> 
	{% endblock %}

	

	

	<!-- Footer -->

	

{% block jsscript %}
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/easing/easing.js' %}"></script>
<script src="{% static 'plugins/rangeslider.js-2.3.0/rangeslider.min.js' %}"></script>
<script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
<script src="{% static 'https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyCIwF204lFZg1y4kPSIhKaHEXMLYxxuMhA' %}"></script>
<script src="{% static 'js/contact.js' %}"></script>
{% endblock %}
</body>
</html>